[package]
name = "peaks"
version = "0.1.0"
authors = ["Dave Poulter <hello@davepoulter.net>"]

[lib]
name = "peaks"

[dependencies]
docopt = "1.0.1"
gdal = "0.4.0"
png = "0.12.0"
serde = "1.0.78"
serde_json = "1.0.27"
serde_derive = "1.0.78"
